INSERT INTO T_RHSTU_ESTADO (ID_ESTADO,SG_ESTADO,NM_ESTADO) 
values (01,'SP','sAo paulo');


------insert São roque-------------
Insert into T_RHSTU_CIDADE ( ID_CIDADE, ID_ESTADO, NM_CIDADE,CD_IBGE,NR_DDD)
VALUES (01,01,'São roque',01,11);

INSERT INTO T_RHSTU_BAIRRO (id_bairro ,ID_CIDADE, NM_BAIRRO , NM_ZONA_BAIRRO)
VALUES ( 03,01,'CENTRO','ZONA LESTE');

INSERT INTO T_RHSTU_LOGRADOURO (ID_LOGRADOURO ,ID_BAIRRO, NM_LOGRADOURO , NR_CEP)
VALUES (5060,03,'Rua da juta',0789456);

Commit
----------------Insert Santos-----------


Insert into T_RHSTU_CIDADE ( ID_CIDADE, ID_ESTADO, NM_CIDADE,CD_IBGE,NR_DDD)
VALUES (02,01,'Santos',02,13);

INSERT INTO T_RHSTU_BAIRRO (id_bairro ,ID_CIDADE, NM_BAIRRO , NM_ZONA_BAIRRO)
VALUES ( 02,01,'Gonzaga','CENTRO');

INSERT INTO T_RHSTU_LOGRADOURO (ID_LOGRADOURO ,ID_BAIRRO, NM_LOGRADOURO , NR_CEP)
VALUES (9090,02,'Rua da paz',0963525);


Commit
------------- iNSERT PACIENTES--------

INSERT INTO  T_RHSTU_PACIENTE (ID_PACIENTE, NM_PACIENTE, NR_CPF, NM_RG,DT_NASCIMENTO, FL_SEXO_BIOLOGICO
,DS_ESCOLARIDADE, DS_ESTADO_CIVIL, NM_GRUPO_SANGUINEO, NR_ALTURA, NR_PESO)Values
(200,'Felipe',052486339, 500012006, TO_DATE('15/05/1995','DD/MM/YYYY'),'M','MEDIO COMPLETO','SOLTEIRO',
'B+',1.80,56);


INSERT INTO T_RHSTU_ENDERECO_PACIENTE (ID_ENDERECO , ID_PACIENTE, ID_LOGRADOURO, NR_LOGRADOURO
,DS_COMPLEMENTO_NUMERO ,DS_PONTO_REFERENCIA , DT_INICIO, DT_FIM) VALUES 
(500,200,9090,01,700,'predio verde', TO_DATE('19/10/2003','DD/MM/YYYY'),
TO_DATE('30/10/2003','DD/MM/YYYY'));


-----------

INSERT INTO  T_RHSTU_PACIENTE (ID_PACIENTE, NM_PACIENTE, NR_CPF, NM_RG,DT_NASCIMENTO, FL_SEXO_BIOLOGICO
,DS_ESCOLARIDADE, DS_ESTADO_CIVIL, NM_GRUPO_SANGUINEO, NR_ALTURA, NR_PESO)Values
(150,'pedro Ferrari',525398247, 400012006, TO_DATE('01/05/1995','DD/MM/YYYY'),'M','MEDIO InCOMPLETO','SOLTEIRO',
'O+',1.86,65);

Select * from T_RHSTU_PACIENTE;

INSERT INTO T_RHSTU_ENDERECO_PACIENTE (ID_ENDERECO , ID_PACIENTE, ID_LOGRADOURO, NR_LOGRADOURO
,DS_COMPLEMENTO_NUMERO ,DS_PONTO_REFERENCIA , DT_INICIO, DT_FIM) VALUES 
(700,150,5060,05,500,'fazneda com cavalo', TO_DATE('15/10/2003','DD/MM/YYYY'),
TO_DATE('30/12/2003','DD/MM/YYYY'));

-------------------cadastro de tipos de contato--------
insert into T_RHSTU_TIPO_CONTATO value  ( ID_TIPO_CONTATO, NM_TIPO_CONTATO, DT_INICIO,DT_FIM)
values (001,'pai',TO_DATE('1/4/1965','DD/MM/YYYY'),TO_DATE('15/08/2001','DD/MM/YYYY'));

insert into T_RHSTU_TIPO_CONTATO value  ( ID_TIPO_CONTATO, NM_TIPO_CONTATO, DT_INICIO,DT_FIM)
values (002,'Mãe',TO_DATE('21/10/1957','DD/MM/YYYY'),TO_DATE('30/08/2011','DD/MM/YYYY'));

insert into T_RHSTU_TIPO_CONTATO value  ( ID_TIPO_CONTATO, NM_TIPO_CONTATO, DT_INICIO,DT_FIM)
values (003,' Esposa',TO_DATE('22/11/1945','DD/MM/YYYY'),TO_DATE('08/08/2016','DD/MM/YYYY'));

insert into T_RHSTU_TIPO_CONTATO value  ( ID_TIPO_CONTATO, NM_TIPO_CONTATO, DT_INICIO,DT_FIM)
values (004,' Outros contatos',TO_DATE('29/12/1950','DD/MM/YYYY'),TO_DATE('20/09/2018','DD/MM/YYYY'));


-------isnert dos valores
Select * from T_RHSTU_PACIENTE;

insert into T_RHSTU_CONTATO_PACIENTE ( ID_PACIENTE, ID_CONTATO, ID_TIPO_CONTATO, NM_CONTATO,NR_DDI ,NR_DDD,NR_TELEFONE)Values
(200,250,001,'robson cruzué',011,55,046350215);

insert into T_RHSTU_CONTATO_PACIENTE ( ID_PACIENTE, ID_CONTATO, ID_TIPO_CONTATO, NM_CONTATO,NR_DDI ,NR_DDD,NR_TELEFONE)Values
(150,250,002,'Chiquinho escarpa',013,395,04635085);

----criação da unidade hospitalar----

insert into  T_RHSTU_UNID_HOSPITALAR ( ID_UNID_HOSPITAL,ID_LOGRADOURO,NM_UNID_HOSPITALAR,
NM_RAZAO_SOCIAL_UNID_HOSP,
DT_FUNDACAO,NR_LOGRADOURO,DS_COMPLEMENTO_NUMERO,DS_PONTO_REFERENCIA,DT_INICIO,DT_TERMINO)
Values
(5000,9090,002,'Hospital legal' ,TO_DATE('15/02/2024','DD/MM/YYYY'),6998, 284,'placa vermelha escrito hospital',
TO_DATE('30/03/1998','DD/MM/YYYY'),null);

insert into T_RHSTU_MEDICO ( CD_MEDICO,NM_MEDICO,NR_CRM,DS_ESPECIALIDADE)values
(500,'thiago',9969697,'pisicologo');
insert into T_RHSTU_MEDICO ( CD_MEDICO,NM_MEDICO,NR_CRM,DS_ESPECIALIDADE)values
(590,'gustavo',98785,'pisiquiatra');


insert into T_RHSTU_MEDICAMENTO (ID_MEDICAMENTO,NM_MEDICAMENTO,DS_DETALHADA_MEDICAMENTO,NR_CODIGO_BARRAS) values
(5589558,'oxandrolona', 'capsula', 785226);

insert into T_RHSTU_MEDICAMENTO (ID_MEDICAMENTO,NM_MEDICAMENTO,DS_DETALHADA_MEDICAMENTO,NR_CODIGO_BARRAS) values
(5589559,'ritalnia', 'venoso', 785266);

insert into T_RHSTU_CONSULTA ( ID_UNID_HOSPITAL,NR_CONSULTA,ID_PACIENTE,CD_MEDICO,DT_HR_CONSULTA,NR_CONSULTORIO) values
(5000,96666,200,500,














-----Uptade-----

insert into T_RHSTU_FORMA_PAGAMENTO (ID_FORMA_PAGTO, NM_FORMA_PAGTO,DS_FORMA_PAGTO, ST_FORMA_PAGTO)
Values (145,'dinheiro','notas de dois reais ','A')

update T_RHSTU_TIPO_CONTATO set DT_FIM = TO_DATE('15/02/2024','DD/MM/YYYY')
WHERE ID_TIPO_CONTATO = 002
update T_RHSTU_FORMA_PAGAMENTO Set ST_FORMA_PAGTO = 'I';



